# Generated by Django 4.2.11 on 2024-03-12 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendars')),
                ('invited_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('invited_contact_non_busy_dates', models.ManyToManyField(blank=True, to='calendars.nonbusydate')),
            ],
        ),
    ]
