# Generated by Django 4.2.11 on 2024-03-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invited_user_non_busy_dates',
            field=models.ManyToManyField(blank=True, null=True, to='calendars.nonbusydate'),
        ),
    ]
